var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":165,"id":24934,"methods":[{"el":44,"sc":5,"sl":39},{"el":52,"sc":5,"sl":46},{"el":58,"sc":5,"sl":54},{"el":62,"sc":5,"sl":60},{"el":66,"sc":5,"sl":64},{"el":84,"sc":5,"sl":72},{"el":110,"sc":5,"sl":86},{"el":126,"sc":5,"sl":112},{"el":137,"sc":5,"sl":128},{"el":163,"sc":5,"sl":145}],"name":"VariableAccessVisitor","sl":37}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_139":{"methods":[{"sl":46}],"name":"testWhileStmtHasCorrectTypes","pass":true,"statements":[{"sl":47}]},"test_293":{"methods":[{"sl":46}],"name":"testIfStmtHasCorrectTypes","pass":true,"statements":[{"sl":47}]},"test_384":{"methods":[{"sl":46}],"name":"testVariableOrConstantDeclaratorParentChildLinks","pass":true,"statements":[{"sl":47}]},"test_449":{"methods":[{"sl":46}],"name":"testSimpleCaseStmtHasCorrectTypes","pass":true,"statements":[{"sl":47}]},"test_562":{"methods":[{"sl":46}],"name":"testForStmtHasCorrectTypes","pass":true,"statements":[{"sl":47}]},"test_704":{"methods":[{"sl":46}],"name":"testExpressionParentChildLinks","pass":true,"statements":[{"sl":47}]},"test_778":{"methods":[{"sl":46}],"name":"testLabelledStmtHasCorrectTypes","pass":true,"statements":[{"sl":47}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [139, 384, 778, 293, 562, 449, 704], [139, 384, 778, 293, 562, 449, 704], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
